# Generated by Django 4.1.1 on 2022-10-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0002_alter_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="user.png",
                null=True,
                upload_to="user_avatar",
                verbose_name="Аватар",
            ),
        ),
    ]
