# Generated by Django 4.1.1 on 2022-10-10 12:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="content",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
