# Generated by Django 4.1.1 on 2022-10-23 21:16

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0003_category_alias"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                ("text", django_ckeditor_5.fields.CKEditor5Field(verbose_name="Text")),
            ],
        ),
    ]
