# Generated by Django 4.1.1 on 2022-10-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0003_post_content"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="delete",
            new_name="is_deleted",
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=70, verbose_name="Заголовок статьи"),
        ),
    ]
