# Generated by Django 4.1.1 on 2022-11-01 19:31

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0004_alter_post_managers_alter_post_image"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="comment",
            managers=[
                ("objects_all", django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="delete",
            new_name="is_deleted",
        ),
    ]
