# Generated by Django 4.1.1 on 2022-10-23 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0004_article"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Article",
        ),
    ]
