# Generated by Django 4.1.1 on 2022-10-27 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "mainapp",
            "0004_rename_comment_comment_text_remove_comment_parent_id_and_more",
        ),
        ("mainapp", "0005_delete_article"),
    ]

    operations = []
