# Generated by Django 4.1.1 on 2022-11-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0006_alter_comment_post_alter_post_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="active",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="активна"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="active",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="активна"
            ),
        ),
    ]
