# Generated by Django 4.1.1 on 2022-11-09 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mainapp", "0007_alter_comment_active_alter_post_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postlikes",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="mainapp.post",
                verbose_name="Название статьи",
            ),
        ),
        migrations.AlterField(
            model_name="postlikes",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
    ]
