# Generated by Django 4.1.1 on 2022-11-10 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0008_alter_postlikes_post_alter_postlikes_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="postlikes",
            name="like_count",
        ),
        migrations.AddField(
            model_name="postlikes",
            name="status",
            field=models.BooleanField(default=True, verbose_name="Статус"),
        ),
    ]
