# Generated by Django 4.1.1 on 2022-11-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DevAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(blank=True, max_length=45, verbose_name='Фамилия')),
                ('first_name', models.CharField(blank=True, max_length=45, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=45, verbose_name='Отчество')),
                ('avatar', models.ImageField(blank=True, default='user.png', null=True, upload_to='user_avatar', verbose_name='Аватар')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('comments', models.TextField(blank=True, max_length=200, verbose_name='O себе')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gb', models.URLField(unique=True, verbose_name='GeekBrains')),
                ('telegramm', models.URLField(unique=True, verbose_name='Telegramm')),
            ],
            options={
                'verbose_name': 'Автор проекта',
                'verbose_name_plural': 'Ваторы проекта',
            },
        ),
    ]
