# Generated by Django 4.1.1 on 2022-11-08 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("devautorapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="devauthor",
            options={
                "verbose_name": "Автор проекта",
                "verbose_name_plural": "Авторы проекта",
            },
        ),
    ]
